#! /bin/bash

source constants.bash

source util.bash

source refresh.bash

source compose.bash

source admin.bash

source service.bash

source domain.bash

source migrate.bash

source upgrade.bash

source usage.bash

source init.bash


#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------
# Main command sorting:
#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------

# verify we have curl, docker, docker-compose
require() {
  local ERRS
  ERRS=""
  for i in $@; do
    if ! command -v $i ] &> /dev/null; then
      ERRS="${ERRS}\nERROR: $SCRIPTNAME requires command $i"
    fi
  done
  if [ ! "x${ERRS}" == "x" ]; then 
    echo -e $ERRS
    exit
  fi
} 
require ls sed curl docker docker-compose

# usage exits this script when done
[ "$#" -lt 1 ] && usage

CMD=$1
shift
case $CMD in 
  compose) 
    compose $@ 
  ;;

  # Exact list of docker-compose commands to pass thru
  build|config|create|down|events|exec|images|kill|logs|pause|port|ps|pull|push|restart|rm|run|scale|start|stop|top|unpause|up) 
    compose $CMD $@
  ;;

  admin) 
    admin $@ 
  ;;

  init) 
    init $@ 
  ;;

  upgrade) 
    upgrade $@ 
  ;;

  domain) 
    domain $@ 
  ;;

  service) 
    service $@ 
  ;;

  migrate) 
    migrate $@ 
  ;;

  refresh) 
    refresh 
  ;;

  help|--help|-h) 
    usage $@ 
  ;;

  *) 
    usage $@
  ;;
esac


